import pygame

OFFSET_DELTA = 3
SCALE_DELTA = 1.03
MOUSE_SCALE_DELTA = 1.03
MIN_PLANETARY_SIZE = 1
ROCKET_MARKER_SIZE = 2
FONT_PATH = 'fonts/Inconsolata.ttf'
FONT_SIZE = 27
WIDGET_MARGIN = 10
TIME_SCALE = 1E2
VERBOSE = False
BUILD_GRAPHICS = False

draw_markers = True
draw_widgets = True
